package com.lixin.hardwarecode.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lixin.hardwarecode.entity.HistoryDevice;
import com.lixin.hardwarecode.entity.AllDeviceAndPhone;

import com.lixin.hardwarecode.greendao.HistoryDeviceDao;
import com.lixin.hardwarecode.greendao.AllDeviceAndPhoneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig historyDeviceDaoConfig;
    private final DaoConfig allDeviceAndPhoneDaoConfig;

    private final HistoryDeviceDao historyDeviceDao;
    private final AllDeviceAndPhoneDao allDeviceAndPhoneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        historyDeviceDaoConfig = daoConfigMap.get(HistoryDeviceDao.class).clone();
        historyDeviceDaoConfig.initIdentityScope(type);

        allDeviceAndPhoneDaoConfig = daoConfigMap.get(AllDeviceAndPhoneDao.class).clone();
        allDeviceAndPhoneDaoConfig.initIdentityScope(type);

        historyDeviceDao = new HistoryDeviceDao(historyDeviceDaoConfig, this);
        allDeviceAndPhoneDao = new AllDeviceAndPhoneDao(allDeviceAndPhoneDaoConfig, this);

        registerDao(HistoryDevice.class, historyDeviceDao);
        registerDao(AllDeviceAndPhone.class, allDeviceAndPhoneDao);
    }
    
    public void clear() {
        historyDeviceDaoConfig.clearIdentityScope();
        allDeviceAndPhoneDaoConfig.clearIdentityScope();
    }

    public HistoryDeviceDao getHistoryDeviceDao() {
        return historyDeviceDao;
    }

    public AllDeviceAndPhoneDao getAllDeviceAndPhoneDao() {
        return allDeviceAndPhoneDao;
    }

}
