package com.lixin.hardwarecode.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lixin.hardwarecode.entity.AllDeviceAndPhone;
import com.lixin.hardwarecode.entity.HistoryDevice;

import com.lixin.hardwarecode.greendao.AllDeviceAndPhoneDao;
import com.lixin.hardwarecode.greendao.HistoryDeviceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig allDeviceAndPhoneDaoConfig;
    private final DaoConfig historyDeviceDaoConfig;

    private final AllDeviceAndPhoneDao allDeviceAndPhoneDao;
    private final HistoryDeviceDao historyDeviceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        allDeviceAndPhoneDaoConfig = daoConfigMap.get(AllDeviceAndPhoneDao.class).clone();
        allDeviceAndPhoneDaoConfig.initIdentityScope(type);

        historyDeviceDaoConfig = daoConfigMap.get(HistoryDeviceDao.class).clone();
        historyDeviceDaoConfig.initIdentityScope(type);

        allDeviceAndPhoneDao = new AllDeviceAndPhoneDao(allDeviceAndPhoneDaoConfig, this);
        historyDeviceDao = new HistoryDeviceDao(historyDeviceDaoConfig, this);

        registerDao(AllDeviceAndPhone.class, allDeviceAndPhoneDao);
        registerDao(HistoryDevice.class, historyDeviceDao);
    }
    
    public void clear() {
        allDeviceAndPhoneDaoConfig.clearIdentityScope();
        historyDeviceDaoConfig.clearIdentityScope();
    }

    public AllDeviceAndPhoneDao getAllDeviceAndPhoneDao() {
        return allDeviceAndPhoneDao;
    }

    public HistoryDeviceDao getHistoryDeviceDao() {
        return historyDeviceDao;
    }

}
